project_id = "msrmlnyzkkupdhanxgyp"

[functions.paystack-initiate]
verify_jwt = false

[functions.paystack-verify]
verify_jwt = false

[functions.purchase-data]
verify_jwt = false

[functions.sync-swift-packages]
verify_jwt = false

[functions.wallet-purchase]
verify_jwt = false

[functions.sms-test]
verify_jwt = false

