-- Backfill Swift package IDs for data products that map to known Swift plans.
UPDATE public.products
SET swift_package_id = CASE
  WHEN network = 'mtn' AND data_volume_mb = 1024 THEN 'yellow_1gb'
  WHEN network = 'mtn' AND data_volume_mb = 2048 THEN 'yellow_2gb'
  WHEN network = 'mtn' AND data_volume_mb = 3072 THEN 'yellow_3gb'
  WHEN network = 'mtn' AND data_volume_mb = 4096 THEN 'yellow_4gb'
  WHEN network = 'mtn' AND data_volume_mb = 5120 THEN 'yellow_5gb'
  WHEN network = 'mtn' AND data_volume_mb = 6144 THEN 'yellow_6gb'
  WHEN network = 'mtn' AND data_volume_mb = 7168 THEN 'yellow_7gb'
  WHEN network = 'mtn' AND data_volume_mb = 8192 THEN 'yellow_8gb'
  WHEN network = 'mtn' AND data_volume_mb = 9216 THEN 'yellow_9gb'
  WHEN network = 'mtn' AND data_volume_mb = 10240 THEN 'yellow_10gb'
  WHEN network = 'mtn' AND data_volume_mb = 15360 THEN 'yellow_15gb'
  WHEN network = 'mtn' AND data_volume_mb = 20480 THEN 'yellow_20gb'
  WHEN network = 'mtn' AND data_volume_mb = 25600 THEN 'yellow_25gb'
  WHEN network = 'mtn' AND data_volume_mb = 30720 THEN 'yellow_30gb'
  WHEN network = 'mtn' AND data_volume_mb = 40960 THEN 'yellow_40gb'
  WHEN network = 'mtn' AND data_volume_mb = 51200 THEN 'yellow_50gb'
  WHEN network = 'mtn' AND data_volume_mb = 102400 THEN 'yellow_100gb'
  WHEN network = 'telecel' AND data_volume_mb = 10240 THEN 'red_10gb'
  WHEN network = 'telecel' AND data_volume_mb = 15360 THEN 'red_15gb'
  WHEN network = 'telecel' AND data_volume_mb = 20480 THEN 'red_20gb'
  WHEN network = 'telecel' AND data_volume_mb = 25600 THEN 'red_25gb'
  WHEN network = 'telecel' AND data_volume_mb = 30720 THEN 'red_30gb'
  WHEN network = 'telecel' AND data_volume_mb = 40960 THEN 'red_40gb'
  WHEN network = 'telecel' AND data_volume_mb = 51200 THEN 'red_50gb'
  WHEN network = 'airteltigo' AND data_volume_mb = 1024 THEN 'blue_1gb'
  WHEN network = 'airteltigo' AND data_volume_mb = 2048 THEN 'blue_2gb'
  WHEN network = 'airteltigo' AND data_volume_mb = 3072 THEN 'blue_3gb'
  WHEN network = 'airteltigo' AND data_volume_mb = 4096 THEN 'blue_4gb'
  WHEN network = 'airteltigo' AND data_volume_mb = 5120 THEN 'blue_5gb'
  WHEN network = 'airteltigo' AND data_volume_mb = 6144 THEN 'blue_6gb'
  WHEN network = 'airteltigo' AND data_volume_mb = 7168 THEN 'blue_7gb'
  WHEN network = 'airteltigo' AND data_volume_mb = 8192 THEN 'blue_8gb'
  WHEN network = 'airteltigo' AND data_volume_mb = 9216 THEN 'blue_9gb'
  ELSE swift_package_id
END
WHERE type = 'data';
