// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msrmlnyzkkupdhanxgyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zcm1sbnl6a2t1cGRoYW54Z3lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5MDU1MTMsImV4cCI6MjA5MDQ4MTUxM30.BZqLyfqCGltxvTrSLnlQ2C90pjTN75EddUVvUq3Z1ws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});